# clk input is from the 100 MHz oscillator on Boolean board
#create_clock -period 10.000 -name gclk [get_ports clk_100MHz]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports clk]

# Set Bank 0 voltage
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

# On-board Slide Switches
set_property -dict {PACKAGE_PIN V2 IOSTANDARD LVCMOS33} [get_ports {sw[0]}]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports {sw[1]}]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD LVCMOS33} [get_ports {sw[2]}]
set_property -dict {PACKAGE_PIN T2 IOSTANDARD LVCMOS33} [get_ports {sw[3]}]
set_property -dict {PACKAGE_PIN T1 IOSTANDARD LVCMOS33} [get_ports {sw[4]}]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS33} [get_ports {sw[5]}]
set_property -dict {PACKAGE_PIN R1 IOSTANDARD LVCMOS33} [get_ports {sw[6]}]
set_property -dict {PACKAGE_PIN P2 IOSTANDARD LVCMOS33} [get_ports {sw[7]}]
set_property -dict {PACKAGE_PIN P1 IOSTANDARD LVCMOS33} [get_ports {sw[8]}]
set_property -dict {PACKAGE_PIN N2 IOSTANDARD LVCMOS33} [get_ports {sw[9]}]
set_property -dict {PACKAGE_PIN N1 IOSTANDARD LVCMOS33} [get_ports {sw[10]}]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports {sw[11]}]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS33} [get_ports {sw[12]}]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVCMOS33} [get_ports {sw[13]}]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {sw[14]}]
set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports {sw[15]}]

# On-board LEDs
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN F1 IOSTANDARD LVCMOS33} [get_ports {led[2]}]
set_property -dict {PACKAGE_PIN F2 IOSTANDARD LVCMOS33} [get_ports {led[3]}]
set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS33} [get_ports {led[4]}]
set_property -dict {PACKAGE_PIN E2 IOSTANDARD LVCMOS33} [get_ports {led[5]}]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports {led[6]}]
set_property -dict {PACKAGE_PIN E5 IOSTANDARD LVCMOS33} [get_ports {led[7]}]
set_property -dict {PACKAGE_PIN E6 IOSTANDARD LVCMOS33} [get_ports {led[8]}]
set_property -dict {PACKAGE_PIN C3 IOSTANDARD LVCMOS33} [get_ports {led[9]}]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports {led[10]}]
set_property -dict {PACKAGE_PIN A2 IOSTANDARD LVCMOS33} [get_ports {led[11]}]
set_property -dict {PACKAGE_PIN B3 IOSTANDARD LVCMOS33} [get_ports {led[12]}]
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports {led[13]}]
set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports {led[14]}]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports {led[15]}]

# On-board Buttons
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports {btn[0]}]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33} [get_ports {btn[1]}]
set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVCMOS33} [get_ports {btn[2]}]
set_property -dict {PACKAGE_PIN J1 IOSTANDARD LVCMOS33} [get_ports {btn[3]}]

# TDC in-out
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33} [get_ports trig_out]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports trig_in]

# UART
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVCMOS33} [get_ports UART_rxd]
set_property -dict {PACKAGE_PIN U11 IOSTANDARD LVCMOS33} [get_ports UART_txd]


# PLACING DELLA TDL (VIVADO non accetta cicli for all'interno dell'xdc!!!)
set_property BEL AFF [get_cells U_FF_INPUT]
set_property LOC SLICE_X7Y0 [get_cells U_FF_INPUT]
set_property LOC SLICE_X7Y1 [get_cells {tdc_carry_chain_i/GEN_CHAIN[0].U_CARRY4}]
set_property LOC SLICE_X7Y2 [get_cells {tdc_carry_chain_i/GEN_CHAIN[1].U_CARRY4}]
set_property LOC SLICE_X7Y3 [get_cells {tdc_carry_chain_i/GEN_CHAIN[2].U_CARRY4}]
set_property LOC SLICE_X7Y4 [get_cells {tdc_carry_chain_i/GEN_CHAIN[3].U_CARRY4}]
set_property LOC SLICE_X7Y5 [get_cells {tdc_carry_chain_i/GEN_CHAIN[4].U_CARRY4}]
set_property LOC SLICE_X7Y6 [get_cells {tdc_carry_chain_i/GEN_CHAIN[5].U_CARRY4}]
set_property LOC SLICE_X7Y7 [get_cells {tdc_carry_chain_i/GEN_CHAIN[6].U_CARRY4}]
set_property LOC SLICE_X7Y8 [get_cells {tdc_carry_chain_i/GEN_CHAIN[7].U_CARRY4}]
set_property LOC SLICE_X7Y9 [get_cells {tdc_carry_chain_i/GEN_CHAIN[8].U_CARRY4}]
set_property LOC SLICE_X7Y10 [get_cells {tdc_carry_chain_i/GEN_CHAIN[9].U_CARRY4}]
set_property LOC SLICE_X7Y11 [get_cells {tdc_carry_chain_i/GEN_CHAIN[10].U_CARRY4}]
set_property LOC SLICE_X7Y12 [get_cells {tdc_carry_chain_i/GEN_CHAIN[11].U_CARRY4}]
set_property LOC SLICE_X7Y13 [get_cells {tdc_carry_chain_i/GEN_CHAIN[12].U_CARRY4}]
set_property LOC SLICE_X7Y14 [get_cells {tdc_carry_chain_i/GEN_CHAIN[13].U_CARRY4}]
set_property LOC SLICE_X7Y15 [get_cells {tdc_carry_chain_i/GEN_CHAIN[14].U_CARRY4}]
set_property LOC SLICE_X7Y16 [get_cells {tdc_carry_chain_i/GEN_CHAIN[15].U_CARRY4}]
set_property LOC SLICE_X7Y17 [get_cells {tdc_carry_chain_i/GEN_CHAIN[16].U_CARRY4}]
set_property LOC SLICE_X7Y18 [get_cells {tdc_carry_chain_i/GEN_CHAIN[17].U_CARRY4}]
set_property LOC SLICE_X7Y19 [get_cells {tdc_carry_chain_i/GEN_CHAIN[18].U_CARRY4}]
set_property LOC SLICE_X7Y20 [get_cells {tdc_carry_chain_i/GEN_CHAIN[19].U_CARRY4}]
set_property LOC SLICE_X7Y21 [get_cells {tdc_carry_chain_i/GEN_CHAIN[20].U_CARRY4}]
set_property LOC SLICE_X7Y22 [get_cells {tdc_carry_chain_i/GEN_CHAIN[21].U_CARRY4}]
set_property LOC SLICE_X7Y23 [get_cells {tdc_carry_chain_i/GEN_CHAIN[22].U_CARRY4}]
set_property LOC SLICE_X7Y24 [get_cells {tdc_carry_chain_i/GEN_CHAIN[23].U_CARRY4}]
set_property LOC SLICE_X7Y25 [get_cells {tdc_carry_chain_i/GEN_CHAIN[24].U_CARRY4}]
set_property LOC SLICE_X7Y26 [get_cells {tdc_carry_chain_i/GEN_CHAIN[25].U_CARRY4}]
set_property LOC SLICE_X7Y27 [get_cells {tdc_carry_chain_i/GEN_CHAIN[26].U_CARRY4}]
set_property LOC SLICE_X7Y28 [get_cells {tdc_carry_chain_i/GEN_CHAIN[27].U_CARRY4}]
set_property LOC SLICE_X7Y29 [get_cells {tdc_carry_chain_i/GEN_CHAIN[28].U_CARRY4}]
set_property LOC SLICE_X7Y30 [get_cells {tdc_carry_chain_i/GEN_CHAIN[29].U_CARRY4}]
set_property LOC SLICE_X7Y31 [get_cells {tdc_carry_chain_i/GEN_CHAIN[30].U_CARRY4}]
set_property LOC SLICE_X7Y32 [get_cells {tdc_carry_chain_i/GEN_CHAIN[31].U_CARRY4}]
set_property LOC SLICE_X7Y33 [get_cells {tdc_carry_chain_i/GEN_CHAIN[32].U_CARRY4}]
set_property LOC SLICE_X7Y34 [get_cells {tdc_carry_chain_i/GEN_CHAIN[33].U_CARRY4}]
set_property LOC SLICE_X7Y35 [get_cells {tdc_carry_chain_i/GEN_CHAIN[34].U_CARRY4}]
set_property LOC SLICE_X7Y36 [get_cells {tdc_carry_chain_i/GEN_CHAIN[35].U_CARRY4}]
set_property LOC SLICE_X7Y37 [get_cells {tdc_carry_chain_i/GEN_CHAIN[36].U_CARRY4}]
set_property LOC SLICE_X7Y38 [get_cells {tdc_carry_chain_i/GEN_CHAIN[37].U_CARRY4}]
set_property LOC SLICE_X7Y39 [get_cells {tdc_carry_chain_i/GEN_CHAIN[38].U_CARRY4}]
set_property LOC SLICE_X7Y40 [get_cells {tdc_carry_chain_i/GEN_CHAIN[39].U_CARRY4}]
set_property LOC SLICE_X7Y41 [get_cells {tdc_carry_chain_i/GEN_CHAIN[40].U_CARRY4}]
set_property LOC SLICE_X7Y42 [get_cells {tdc_carry_chain_i/GEN_CHAIN[41].U_CARRY4}]
set_property LOC SLICE_X7Y43 [get_cells {tdc_carry_chain_i/GEN_CHAIN[42].U_CARRY4}]
set_property LOC SLICE_X7Y44 [get_cells {tdc_carry_chain_i/GEN_CHAIN[43].U_CARRY4}]
set_property LOC SLICE_X7Y45 [get_cells {tdc_carry_chain_i/GEN_CHAIN[44].U_CARRY4}]
set_property LOC SLICE_X7Y46 [get_cells {tdc_carry_chain_i/GEN_CHAIN[45].U_CARRY4}]
set_property LOC SLICE_X7Y47 [get_cells {tdc_carry_chain_i/GEN_CHAIN[46].U_CARRY4}]
set_property LOC SLICE_X7Y48 [get_cells {tdc_carry_chain_i/GEN_CHAIN[47].U_CARRY4}]
set_property LOC SLICE_X7Y49 [get_cells {tdc_carry_chain_i/GEN_CHAIN[48].U_CARRY4}]
set_property LOC SLICE_X7Y50 [get_cells {tdc_carry_chain_i/GEN_CHAIN[49].U_CARRY4}]
set_property LOC SLICE_X7Y51 [get_cells {tdc_carry_chain_i/GEN_CHAIN[50].U_CARRY4}]
set_property LOC SLICE_X7Y52 [get_cells {tdc_carry_chain_i/GEN_CHAIN[51].U_CARRY4}]
set_property LOC SLICE_X7Y53 [get_cells {tdc_carry_chain_i/GEN_CHAIN[52].U_CARRY4}]
set_property LOC SLICE_X7Y54 [get_cells {tdc_carry_chain_i/GEN_CHAIN[53].U_CARRY4}]
set_property LOC SLICE_X7Y55 [get_cells {tdc_carry_chain_i/GEN_CHAIN[54].U_CARRY4}]
set_property LOC SLICE_X7Y56 [get_cells {tdc_carry_chain_i/GEN_CHAIN[55].U_CARRY4}]
set_property LOC SLICE_X7Y57 [get_cells {tdc_carry_chain_i/GEN_CHAIN[56].U_CARRY4}]
set_property LOC SLICE_X7Y58 [get_cells {tdc_carry_chain_i/GEN_CHAIN[57].U_CARRY4}]
set_property LOC SLICE_X7Y59 [get_cells {tdc_carry_chain_i/GEN_CHAIN[58].U_CARRY4}]
set_property LOC SLICE_X7Y60 [get_cells {tdc_carry_chain_i/GEN_CHAIN[59].U_CARRY4}]
set_property LOC SLICE_X7Y61 [get_cells {tdc_carry_chain_i/GEN_CHAIN[60].U_CARRY4}]
set_property LOC SLICE_X7Y62 [get_cells {tdc_carry_chain_i/GEN_CHAIN[61].U_CARRY4}]
set_property LOC SLICE_X7Y63 [get_cells {tdc_carry_chain_i/GEN_CHAIN[62].U_CARRY4}]
set_property LOC SLICE_X7Y64 [get_cells {tdc_carry_chain_i/GEN_CHAIN[63].U_CARRY4}]
set_property LOC SLICE_X7Y65 [get_cells {tdc_carry_chain_i/GEN_CHAIN[64].U_CARRY4}]
set_property LOC SLICE_X7Y66 [get_cells {tdc_carry_chain_i/GEN_CHAIN[65].U_CARRY4}]
set_property LOC SLICE_X7Y67 [get_cells {tdc_carry_chain_i/GEN_CHAIN[66].U_CARRY4}]
set_property LOC SLICE_X7Y68 [get_cells {tdc_carry_chain_i/GEN_CHAIN[67].U_CARRY4}]
set_property LOC SLICE_X7Y69 [get_cells {tdc_carry_chain_i/GEN_CHAIN[68].U_CARRY4}]
set_property LOC SLICE_X7Y70 [get_cells {tdc_carry_chain_i/GEN_CHAIN[69].U_CARRY4}]
set_property LOC SLICE_X7Y71 [get_cells {tdc_carry_chain_i/GEN_CHAIN[70].U_CARRY4}]
set_property LOC SLICE_X7Y72 [get_cells {tdc_carry_chain_i/GEN_CHAIN[71].U_CARRY4}]
set_property LOC SLICE_X7Y73 [get_cells {tdc_carry_chain_i/GEN_CHAIN[72].U_CARRY4}]
set_property LOC SLICE_X7Y74 [get_cells {tdc_carry_chain_i/GEN_CHAIN[73].U_CARRY4}]
set_property LOC SLICE_X7Y75 [get_cells {tdc_carry_chain_i/GEN_CHAIN[74].U_CARRY4}]
set_property LOC SLICE_X7Y76 [get_cells {tdc_carry_chain_i/GEN_CHAIN[75].U_CARRY4}]
set_property LOC SLICE_X7Y77 [get_cells {tdc_carry_chain_i/GEN_CHAIN[76].U_CARRY4}]
set_property LOC SLICE_X7Y78 [get_cells {tdc_carry_chain_i/GEN_CHAIN[77].U_CARRY4}]
set_property LOC SLICE_X7Y79 [get_cells {tdc_carry_chain_i/GEN_CHAIN[78].U_CARRY4}]
set_property LOC SLICE_X7Y80 [get_cells {tdc_carry_chain_i/GEN_CHAIN[79].U_CARRY4}]
set_property LOC SLICE_X7Y81 [get_cells {tdc_carry_chain_i/GEN_CHAIN[80].U_CARRY4}]
set_property LOC SLICE_X7Y82 [get_cells {tdc_carry_chain_i/GEN_CHAIN[81].U_CARRY4}]
set_property LOC SLICE_X7Y83 [get_cells {tdc_carry_chain_i/GEN_CHAIN[82].U_CARRY4}]
set_property LOC SLICE_X7Y84 [get_cells {tdc_carry_chain_i/GEN_CHAIN[83].U_CARRY4}]
set_property LOC SLICE_X7Y85 [get_cells {tdc_carry_chain_i/GEN_CHAIN[84].U_CARRY4}]
set_property LOC SLICE_X7Y86 [get_cells {tdc_carry_chain_i/GEN_CHAIN[85].U_CARRY4}]
set_property LOC SLICE_X7Y87 [get_cells {tdc_carry_chain_i/GEN_CHAIN[86].U_CARRY4}]
set_property LOC SLICE_X7Y88 [get_cells {tdc_carry_chain_i/GEN_CHAIN[87].U_CARRY4}]
set_property LOC SLICE_X7Y89 [get_cells {tdc_carry_chain_i/GEN_CHAIN[88].U_CARRY4}]
set_property LOC SLICE_X7Y90 [get_cells {tdc_carry_chain_i/GEN_CHAIN[89].U_CARRY4}]
set_property LOC SLICE_X7Y91 [get_cells {tdc_carry_chain_i/GEN_CHAIN[90].U_CARRY4}]
set_property LOC SLICE_X7Y92 [get_cells {tdc_carry_chain_i/GEN_CHAIN[91].U_CARRY4}]
set_property LOC SLICE_X7Y93 [get_cells {tdc_carry_chain_i/GEN_CHAIN[92].U_CARRY4}]
set_property LOC SLICE_X7Y94 [get_cells {tdc_carry_chain_i/GEN_CHAIN[93].U_CARRY4}]
set_property LOC SLICE_X7Y95 [get_cells {tdc_carry_chain_i/GEN_CHAIN[94].U_CARRY4}]
set_property LOC SLICE_X7Y96 [get_cells {tdc_carry_chain_i/GEN_CHAIN[95].U_CARRY4}]
set_property LOC SLICE_X7Y97 [get_cells {tdc_carry_chain_i/GEN_CHAIN[96].U_CARRY4}]
set_property LOC SLICE_X7Y98 [get_cells {tdc_carry_chain_i/GEN_CHAIN[97].U_CARRY4}]
set_property LOC SLICE_X7Y99 [get_cells {tdc_carry_chain_i/GEN_CHAIN[98].U_CARRY4}]
set_property LOC SLICE_X7Y100 [get_cells {tdc_carry_chain_i/GEN_CHAIN[99].U_CARRY4}]
set_property LOC SLICE_X7Y101 [get_cells {tdc_carry_chain_i/GEN_CHAIN[100].U_CARRY4}]
set_property LOC SLICE_X7Y102 [get_cells {tdc_carry_chain_i/GEN_CHAIN[101].U_CARRY4}]
set_property LOC SLICE_X7Y103 [get_cells {tdc_carry_chain_i/GEN_CHAIN[102].U_CARRY4}]
set_property LOC SLICE_X7Y104 [get_cells {tdc_carry_chain_i/GEN_CHAIN[103].U_CARRY4}]
set_property LOC SLICE_X7Y105 [get_cells {tdc_carry_chain_i/GEN_CHAIN[104].U_CARRY4}]
set_property LOC SLICE_X7Y106 [get_cells {tdc_carry_chain_i/GEN_CHAIN[105].U_CARRY4}]
set_property LOC SLICE_X7Y107 [get_cells {tdc_carry_chain_i/GEN_CHAIN[106].U_CARRY4}]
set_property LOC SLICE_X7Y108 [get_cells {tdc_carry_chain_i/GEN_CHAIN[107].U_CARRY4}]
set_property LOC SLICE_X7Y109 [get_cells {tdc_carry_chain_i/GEN_CHAIN[108].U_CARRY4}]
set_property LOC SLICE_X7Y110 [get_cells {tdc_carry_chain_i/GEN_CHAIN[109].U_CARRY4}]
set_property LOC SLICE_X7Y111 [get_cells {tdc_carry_chain_i/GEN_CHAIN[110].U_CARRY4}]
set_property LOC SLICE_X7Y112 [get_cells {tdc_carry_chain_i/GEN_CHAIN[111].U_CARRY4}]
set_property LOC SLICE_X7Y113 [get_cells {tdc_carry_chain_i/GEN_CHAIN[112].U_CARRY4}]
set_property LOC SLICE_X7Y114 [get_cells {tdc_carry_chain_i/GEN_CHAIN[113].U_CARRY4}]
set_property LOC SLICE_X7Y115 [get_cells {tdc_carry_chain_i/GEN_CHAIN[114].U_CARRY4}]
set_property LOC SLICE_X7Y116 [get_cells {tdc_carry_chain_i/GEN_CHAIN[115].U_CARRY4}]
set_property LOC SLICE_X7Y117 [get_cells {tdc_carry_chain_i/GEN_CHAIN[116].U_CARRY4}]
set_property LOC SLICE_X7Y118 [get_cells {tdc_carry_chain_i/GEN_CHAIN[117].U_CARRY4}]
set_property LOC SLICE_X7Y119 [get_cells {tdc_carry_chain_i/GEN_CHAIN[118].U_CARRY4}]
set_property LOC SLICE_X7Y120 [get_cells {tdc_carry_chain_i/GEN_CHAIN[119].U_CARRY4}]
set_property LOC SLICE_X7Y121 [get_cells {tdc_carry_chain_i/GEN_CHAIN[120].U_CARRY4}]
set_property LOC SLICE_X7Y122 [get_cells {tdc_carry_chain_i/GEN_CHAIN[121].U_CARRY4}]
set_property LOC SLICE_X7Y123 [get_cells {tdc_carry_chain_i/GEN_CHAIN[122].U_CARRY4}]
set_property LOC SLICE_X7Y124 [get_cells {tdc_carry_chain_i/GEN_CHAIN[123].U_CARRY4}]
set_property LOC SLICE_X7Y125 [get_cells {tdc_carry_chain_i/GEN_CHAIN[124].U_CARRY4}]
set_property LOC SLICE_X7Y126 [get_cells {tdc_carry_chain_i/GEN_CHAIN[125].U_CARRY4}]
set_property LOC SLICE_X7Y127 [get_cells {tdc_carry_chain_i/GEN_CHAIN[126].U_CARRY4}]
set_property LOC SLICE_X7Y128 [get_cells {tdc_carry_chain_i/GEN_CHAIN[127].U_CARRY4}]


# False path sul segnale HIT verso il FF di ingresso (trig_in entra in un input dedicato ad un clock, questo non piace molto al sintetizzatore)
# 1 - Prima definisci il clock
create_clock -period 10.000 -name trig_clk [get_ports trig_in]
create_clock -period 15.000 -name ring_osc_clk1 [get_nets ring_osc_i/osc_o]

set_clock_groups -asynchronous -group [get_clocks ring_osc_clk1] -group [get_clocks clk_out1_clk_0]
set_false_path -from [get_clocks ring_osc_clk1]

#set_false_path -from [get_clocks trig_clk] -to [get_pins "U_FF_INPUT/C"]
set_false_path -from [get_clocks trig_clk]

# 3 - Infine impedisci il BUFG
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets -of_objects [get_ports trig_in]]

# ring oscillator (ignorare il loop combinatorio e non fare time analysis)
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {ring_osc_i/ci[0]}]